let txt = "ahjbsdxmnsdv";
let txt0 = txt.length
console.log(txt0);
let txt1="blah";
let txt2 = txt1.replace("blah","bgu");
console.log(txt2);

let txt3 = txt1.concat(" and ",txt2);
console.log(txt3);

const d = new Date();
var h=d.getHours();

console.log(d);

/*function greet(){
if(h<12){
    let greeting = "Good Morning";
    console.log(greeting);
document.getElementById("1").innerHTML = greeting;
}
else if(h <18){
    let greeting = "Good Afternoon";
    console.log(greeting2);
document.getElementById("1").innerHTML = greeting2;
} 
else{
    let greeting = "Good Morning";
    console.log(greeting3);
document.getElementById("1").innerHTML = greeting3;
}
let cars = ["Toyota", 'Honda', 'Mazda'];
console.log(cars);
}*/

Function stopMotion() {
    let imgs = [
        "imgs/LANDSCAPE1.jpg",
        "imgs/LANDSCAPE2.jpg",
        "imgs/LANDSCAPE3.jpg",
    ]
}
console.log(Image)
